// Reads the real, editable web/index.html and generates a committed TS
// module exporting it as a string, so the app never depends on a web
// server running during the demo. Re-run after editing web/index.html:
//   npm run build:webapp
const fs = require('fs');
const path = require('path');

const source = path.join(__dirname, '..', '..', 'web', 'index.html');
const target = path.join(__dirname, '..', 'src', 'infrastructure', 'webAppHtml.ts');

const html = fs.readFileSync(source, 'utf8');

const output = `// AUTO-GENERATED from web/index.html by scripts/build-web-app.js.
// Do not edit this file directly — edit web/index.html and run
// \`npm run build:webapp\` to regenerate.

// Module-level constant (not an inline literal) so the reference is stable
// across renders and the WebView never reloads because \`source\` changed.
export const webAppSource: { html: string } = {
  html: ${JSON.stringify(html)},
};
`;

fs.writeFileSync(target, output);
console.log(`Wrote ${path.relative(process.cwd(), target)}`);
